#cloud-config
autoinstall:
  version: 1
  network:
    version: 2
    ethernets:
      enp1s0:
        dhcp4: false
        dhcp6: false
        optional: true
    bridges:
      br0:
        dhcp4: true
        dhcp6: false
        accept-ra: false
        link-local: []
        interfaces:
          - enp1s0
  storage:
    layout:
      name: lvm
      sizing-policy: all
  timezone: "UTC"
  keyboard:
    layout: "us"
  ssh:
    install-server: yes
    allow-pw: yes
  late-commands:
    # Configure grub to use serial console for display
    - curtin in-target -- sed -ie 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=30/' /etc/default/grub
    - curtin in-target -- sed -ie 's/GRUB_TIMEOUT_STYLE=.*/GRUB_TIMEOUT=countdown/' /etc/default/grub
    - curtin in-target -- sed -ie 's/GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX="console=tty1 console=ttyS0,115200n8 systemd.wants=serial-getty@ttyS0"/' /etc/default/grub
    - curtin in-target -- sed -ie 's/#GRUB_TERMINAL=.*/GRUB_TERMINAL="console serial"/' /etc/default/grub
    - curtin in-target -- update-grub
  user-data: # cloud-init starts here
    hostname: robot00
    users:
      - name: automat
        uid: 63112
        primary_group: users
        groups: users
        shell: /bin/bash
        plain_text_passwd: superseekret
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: False
        ssh_authorized_keys:
          # taylor
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINy9cJcJl8oN6bRtcBc4RZq8f/T6P1AFR3YS1YRYi5YY sheila
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINRK4hkcpUiaSkiLEytgwMYcKylBioXPLx1TnwJFrLPl mahowald
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHGTw44QBehDXY6ebitrYydyAAhDFLBSkQ59RovcVsvX joan

    chpasswd: { expire: false }
    ssh_pwauth: true
