#cloud-config
autoinstall:
  version: 1
  network:
    version: 2
    renderer: NetworkManager
    ethernets:
      eno1:
        dhcp4: false
        dhcp6: false
        optional: true
    bridges:
      br0:
        interfaces:
          - eno1
        dhcp4: true
        dhcp6: false
        accept-ra: false
        link-local: []
        parameters:
          stp: false
          forward-delay: 0
  storage:
    config:
    - transport: pcie
      preserve: true
      id: nvme-controller-nvme2
      type: nvme_controller
    - ptable: gpt
      serial: KINGSTON_SNVS2000G_50026B768596C4FC_1
      wwn: eui.00000000000000000026b768596c4fc5
      nvme_controller: nvme-controller-nvme2
      path: /dev/nvme2n1
      preserve: true
      name: ''
      grub_device: false
      id: disk-nvme2n1
      type: disk
    - device: disk-nvme2n1
      size: 1127219200
      flag: boot
      number: 1
      preserve: true
      grub_device: true
      offset: 1048576
      partition_type: c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      path: /dev/nvme2n1p1
      uuid: 7220f12b-2a96-41b2-8d94-93c19a41ea09
      id: partition-nvme2n1p1
      type: partition
    - device: disk-nvme2n1
      size: 1999269527552
      wipe: superblock
      number: 2
      preserve: false
      offset: 1128267776
      path: /dev/nvme2n1p2
      id: partition-0
      type: partition
    - fstype: ext4
      volume: partition-0
      preserve: false
      id: format-0
      type: format
    - path: /
      device: format-0
      id: mount-0
      type: mount
    - fstype: vfat
      volume: partition-nvme2n1p1
      preserve: true
      id: format-partition-nvme2n1p1
      type: format
    - path: /boot/efi
      device: format-partition-nvme2n1p1
      id: mount-1
      type: mount
  timezone: America/New_York
  keyboard:
    layout: us
  kernel:
    flavor: hwe
  ssh:
    install-server: true
    allow-pw: true
  packages:
    - openssh-server
  late-commands:
    # Because we're using preserve_hostname to allow manual setting of the
    # hostname, set an initial hostname manually - the identity block requires
    # a username and it doesn't support flexible enough configuration
    - curtin in-target -- sh -c 'echo pxe > /etc/hostname'
    # Seed the already ran marker for gnome-initial-setup so new users inherit
    - curtin in-target -- mkdir -p /etc/skel/.config
    - curtin in-target -- touch /etc/skel/.config/gnome-initial-setup-done
    # Disable unattended upgrades
    - curtin in-target -- systemctl disable apt-daily.timer
    - curtin in-target -- systemctl disable apt-daily-upgrade.timer
    - curtin in-target -- systemctl mask apt-daily.service
    - curtin in-target -- systemctl mask apt-daily-upgrade.service
    # Configure unattended-upgrades to not run
    - curtin in-target -- sh -c 'echo "APT::Periodic::Update-Package-Lists \"0\";" > /etc/apt/apt.conf.d/20auto-upgrades'
    - curtin in-target -- sh -c 'echo "APT::Periodic::Unattended-Upgrade \"0\";" >> /etc/apt/apt.conf.d/20auto-upgrades'
    - curtin in-target -- sh -c 'echo "APT::Periodic::Download-Upgradeable-Packages \"0\";" >> /etc/apt/apt.conf.d/20auto-upgrades'
    - curtin in-target -- sh -c 'echo "APT::Periodic::AutocleanInterval \"0\";" >> /etc/apt/apt.conf.d/20auto-upgrades'
    # Disable update-notifier
    - curtin in-target -- systemctl disable update-notifier-download.timer || true
    - curtin in-target -- systemctl disable update-notifier-motd.timer || true
  user-data: # cloud-init starts here
    preserve_hostname: true
    users:
      # Temporary user used for initial bootstrapping with CM tool
      - name: autobot
        uid: 63112
        primary_group: users
        groups: users
        shell: /bin/bash
        # Testing with a plaintext password
        plain_text_passwd: superseekret
        # Replace with your generated salted SHA-512 hash using 'openssl passwd -6'
        # passwd: "$6$W32sh2s3EDp01J$ajF/6iHYX1Ef2pF5mPi..zBFiU4Qzvnif.hT2MB.dZ9mSx6txdPiz..."
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        ssh_authorized_keys:
          # taylor
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEWerEkujoB7ipGnWJwnPGFu3DuUQJtc1zB6YqjGRziE sheila
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINRK4hkcpUiaSkiLEytgwMYcKylBioXPLx1TnwJFrLPl mahowald
    chpasswd: {expire: false}
    ssh_pwauth: true
    # DBus doesn't appear to be active in late-commands, so wait to configure
    # power saving defaults until cloud-init time, plus cloud-init has
    # a nice module to write out files
    write_files:
      # Configure system-wide defaults to disable screen blanking
      - path: /etc/dconf/db/local.d/00-screensaver
        content: |
          [org/gnome/desktop/session]
          idle-delay=uint32 0

          [org/gnome/desktop/screensaver]
          lock-enabled=false
          idle-activation-enabled=false

          [org/gnome/settings-daemon/plugins/power]
          sleep-inactive-ac-type="nothing"
          sleep-inactive-battery-type="nothing"
          idle-dim=false
      # Configure system to refer to user settings in ~/.config/dconf/user
      # database first, then look for system-wide defaults in
      # /etc/dconf/db/local
      - path: /etc/dconf/profile/user
        content: |
          user-db:user
          system-db:local
    runcmd:
      # Update the GNOME system database with the changes to /etc/dconf
      # above 
      - dconf update
